#!/bin/bash

# postinst
#
# Copyright (C) 2014 Kano Computing Ltd.
# License: http://www.gnu.org/licenses/gpl-2.0.txt GNU General Public License v2
#

lightdm_config=/etc/lightdm/lightdm.conf

case "$1" in
    configure)

        # Switch to use the Kano Greeter
        sed -i 's/^\s*\(greeter-session\=\).*/\1kano-greeter/' "$lightdm_config"

        ;;
esac

#DEBHELPER#

exit 0
