#!/bin/bash

# postrm
#
# Copyright (C) 2014 Kano Computing Ltd.
# License:   http://www.gnu.org/licenses/gpl-2.0.txt GNU General Public License v2
#

lightdm_config=/etc/lightdm/lightdm.conf

case "$1" in
    remove|upgrade)

        # Revert to the default greeter
        sed -i 's/^\s*\(greeter-session\=\).*/\1lightdm-greeter/' "$lightdm_config"

        ;;
esac


#DEBHELPER#

exit 0
