#!/bin/bash

# postinst
#
# Copyright (C) 2014 Kano Computing Ltd.
# License: http://www.gnu.org/licenses/gpl-2.0.txt GNU General Public License v2
#

lightdm_config=/etc/lightdm/lightdm.conf
kano_init_sudoers=/etc/sudoers.d/kano-init_conf

case "$1" in
    configure)

        # Switch to use the Kano Greeter
        sed -i 's/^\s*\(greeter-session\=\).*/\1kano-greeter/' "$lightdm_config"

        # Allow the greeter to run kano-init
        sed -i '$a%lightdm    ALL=(root) NOPASSWD: /usr/bin/kano-init' "$kano_init_sudoers"

        # Allow the greeter to run kano-greeter-account for Kano World sync
        sed -i '$a%lightdm    ALL=(root) NOPASSWD: /usr/bin/kano-greeter-account' "$kano_init_sudoers"

        # Allow users to switch to virtual console terminals from the greeter
        sed -i '$a%lightdm    ALL=(root) NOPASSWD: /bin/chvt' "$kano_init_sudoers"

        # Fix permisssions so that lightdm can start the greeter (this actually seems to be a bug in lightm)
        chown lightdm:lightdm /var/lib/lightdm

        # Add the lightdm user to the shadow group, so that he can authenticate system users via PAM
        usermod -a -G shadow lightdm

        ;;
esac

#DEBHELPER#

exit 0
